language: node_js
node_js:
- '9'
env:
  global:
    secure: MjCyMn7p/hWlOIQ5WR42G2rkt1P3dof1bYJ1+6y0hB1UTKZ1JhVI7nAbTuTDmJ95IZrTlFMFjXIoZ2dVF6axnEmAduUkZbKIDDN2wqI1Uoyz5XLzJCHRQar0i4o8eIJ6+8SiMosy43qywOfdreKVkTrwqKreOYJTNOnVvmyrE4/Pv2FEvptRqdbhLXCAw4I0eL+dnhY/DmSUK09rjS7pmwRTlNGjkETrV5HkaZNJVhN5vQ6duqdDBCwhptzS88Fm9e6rsQ6mrgVqZFgJ+bEoSrYLKg/lfrSet4lP3zdCq/u7O6Io6mFFTm5WyQLmmHdt/wNwjl0LJpL+dGNC/yHD1NeIYCNxkxvm03VvoWEFDECE8AyiRNOYe4NS3GffLe+2CgEreD4YJEml0g2qcP8W1IzZDQWy1qkFN/zMwyW1u32flJhjtqVIjyOhmINcCHNn7IlHUneMZWRBGGcMvhfr4fHQxhvlWSkrHdgLC249LuH1oSMfDrY3TakzbMjQxVyNkAT2cntW4UOzbj4ueGR7KfZwEE0TK+T8a4nXTdcqZS3637kfxIRKKb0H7NEWxxcSAn1CJsYmWkqrKDlekKWY4iXi8Uusc6LlJuSRI8Zti2N9pUrBhXOHexNek3G9ackB+DOM3pmJrUnWHaogQ81OiBJBc1/wLgR7lKEPJfajSbI=
