branch-defaults:
  master:
    environment: backend-kernell-challenge-env
    group_suffix: null
global:
  application_name: backend-kernell-challenge
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 18.06.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
