branch-defaults:
  master:
    environment: test-env
global:
  application_name: backend-kernell-challenge
  default_platform: Docker 18.06.1-ce
  default_region: us-east-1
  profile: eb-cli
  sc: git
